# Generated by Django 6.0.3 on 2026-04-14 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_assistant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'project',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CoordinatorXProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_projects', to=settings.AUTH_USER_MODEL, verbose_name='Coordinador')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinators', to='projects.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Coordinador por Proyecto',
                'verbose_name_plural': 'Coordinadores por Proyecto',
                'db_table': 'coordinator_x_project',
                'constraints': [models.UniqueConstraint(fields=('coordinator', 'project'), name='uq_coordinator_project')],
            },
        ),
        migrations.CreateModel(
            name='AssistantXProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_projects', to='users.assistant', verbose_name='Asistente')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='projects.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Asistente por Proyecto',
                'verbose_name_plural': 'Asistentes por Proyecto',
                'db_table': 'assistant_x_project',
                'constraints': [models.UniqueConstraint(fields=('assistant', 'project'), name='uq_assistant_project')],
            },
        ),
    ]
