# Generated by Django 6.0.3 on 2026-03-11 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Coordinador de proyecto que supervisa a este asistente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_assistants', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
    ]
