# Generated by ChatGPT on 2026-02-03

from django.db import migrations


def seed_allowed_ip_ranges(apps, schema_editor):
    AllowedIPRange = apps.get_model('users', 'AllowedIPRange')
    defaults = [
        ("127.0.0.0/8", "Loopback IPv4"),
        ("::1/128", "Loopback IPv6"),
        ("192.168.0.0/16", "Red privada común"),
        ("10.0.0.0/8", "Red privada común"),
    ]

    for network, description in defaults:
        AllowedIPRange.objects.get_or_create(
            network=network,
            defaults={"description": description, "is_active": True},
        )


def unseed_allowed_ip_ranges(apps, schema_editor):
    AllowedIPRange = apps.get_model('users', 'AllowedIPRange')
    AllowedIPRange.objects.filter(
        network__in=["127.0.0.0/8", "::1/128", "192.168.0.0/16", "10.0.0.0/8"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_allowediprange'),
    ]

    operations = [
        migrations.RunPython(seed_allowed_ip_ranges, unseed_allowed_ip_ranges),
    ]
