# Generated by Django 6.0.2 on 2026-02-05 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_seed_allowed_ip_ranges'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllowedIPRange',
        ),
        migrations.AddField(
            model_name='assistant',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Coordinador de proyecto que supervisa a este asistente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_assistants', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
    ]
