# Generated by Django 6.0.3 on 2026-04-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_assistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='needs_password_change',
            field=models.BooleanField(default=False, verbose_name='Necesita cambio de contraseña'),
        ),
    ]
