# Generated by Django 6.0.3 on 2026-04-08 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_assistant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLogStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('is_final', models.BooleanField(default=False, verbose_name='¿Es estado final?')),
            ],
            options={
                'verbose_name': 'Estado de Registro',
                'verbose_name_plural': 'Estados de Registros',
                'db_table': 'time_log_status',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(verbose_name='Entrada')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Salida')),
                ('work_description', models.TextField(blank=True, default='', verbose_name='Descripción del trabajo')),
                ('break_minutes', models.PositiveIntegerField(default=0, verbose_name='Minutos de descanso usados')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de decisión')),
                ('decision_comment', models.TextField(blank=True, default='', verbose_name='Comentario de decisión')),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelogs', to='users.assistant', verbose_name='Asistente')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timelogs', to=settings.AUTH_USER_MODEL, verbose_name='Decidido por')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='time_logs.timelogstatus', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Registro de Horas',
                'verbose_name_plural': 'Registros de Horas',
                'db_table': 'time_log',
                'ordering': ['-check_in'],
            },
        ),
    ]
