# Generated by Django 6.0.3 on 2026-04-14 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('time_logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='activities',
            field=models.TextField(blank=True, default='', verbose_name='Actividades realizadas'),
        ),
        migrations.AddField(
            model_name='timelog',
            name='manager_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_time_logs', to=settings.AUTH_USER_MODEL, verbose_name='Encargado'),
        ),
        migrations.AddField(
            model_name='timelog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_logs', to='projects.project', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='decision_comment',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Notas'),
        ),
    ]
