# Generated by Django 6.0.3 on 2026-04-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_logs', '0002_timelog_activities_timelog_manager_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='closed_by',
            field=models.CharField(blank=True, choices=[('USER', 'Usuario'), ('SYSTEM', 'Sistema')], default=None, max_length=10, null=True, verbose_name='Cerrado por'),
        ),
    ]
