# Generated by Django 6.0.3 on 2026-05-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_logs', '0003_timelog_closed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='review_status',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='reviewed_time_logs',
                to='time_logs.timelogstatus',
                verbose_name='Estado de revisión',
            ),
        ),
    ]
