# Generated by ChatGPT on 2026-02-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_seed_allowed_ip_ranges'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='AllowedIPRange',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('network', models.CharField(help_text='Formato CIDR (ej: 192.168.1.0/24) o IP individual (ej: 192.168.1.1)', max_length=50, unique=True, verbose_name='Red o IP (CIDR)')),
                        ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                        ('is_active', models.BooleanField(default=True, verbose_name='Está activo')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                        ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                    ],
                    options={
                        'verbose_name': 'Rango IP Permitido',
                        'verbose_name_plural': 'Rangos IP Permitidos',
                        'db_table': 'allowed_ip_range',
                        'ordering': ['-is_active', 'network'],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
