# Generated by Django 6.0.2 on 2026-02-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la actividad')),
                ('category', models.CharField(max_length=50, verbose_name='Categoría')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está activa')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'activity',
                'ordering': ['category', 'name'],
            },
        ),
    ]
