# Generated by Django 6.0.2 on 2026-02-03 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayReportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_start_time', models.TimeField(blank=True, null=True, verbose_name='Nueva hora de inicio')),
                ('new_end_time', models.TimeField(blank=True, null=True, verbose_name='Nueva hora de fin')),
                ('new_status', models.CharField(blank=True, choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], max_length=20, null=True, verbose_name='Nuevo estado')),
                ('notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='Notas del cambio')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del cambio')),
                ('manager', models.CharField(blank=True, max_length=50, null=True, verbose_name='Manager')),
            ],
            options={
                'verbose_name': 'Historial de Reporte',
                'verbose_name_plural': 'Historial de Reportes',
                'db_table': 'day_report_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='DayReported',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de fin')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='Notas')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('manager', models.CharField(blank=True, max_length=50, null=True, verbose_name='Manager que aprobó/rechazó')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day_reports', to='activities.activity', verbose_name='Actividad')),
            ],
            options={
                'verbose_name': 'Reporte Diario',
                'verbose_name_plural': 'Reportes Diarios',
                'db_table': 'day_reported',
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
