# Generated by Django 6.0.2 on 2026-02-03 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dayreported',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_reports', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='dayreporthistory',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='activities.activity', verbose_name='Actividad'),
        ),
        migrations.AddField(
            model_name='dayreporthistory',
            name='changed_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_changes', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='dayreporthistory',
            name='day_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='reports.dayreported', verbose_name='Reporte'),
        ),
        migrations.AddIndex(
            model_name='dayreported',
            index=models.Index(fields=['user', 'date'], name='day_reporte_user_id_9e3f0e_idx'),
        ),
        migrations.AddIndex(
            model_name='dayreported',
            index=models.Index(fields=['date'], name='day_reporte_date_afa5ac_idx'),
        ),
        migrations.AddIndex(
            model_name='dayreported',
            index=models.Index(fields=['status'], name='day_reporte_status_946931_idx'),
        ),
        migrations.AddIndex(
            model_name='dayreporthistory',
            index=models.Index(fields=['day_report', 'changed_at'], name='day_report__day_rep_dbcdb7_idx'),
        ),
    ]
