# Generated by Django 6.0.3 on 2026-04-08 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_assistant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='Dirección IP')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'IP Autorizada',
                'verbose_name_plural': 'IPs Autorizadas',
                'db_table': 'authorized_ip',
            },
        ),
        migrations.CreateModel(
            name='IpExceptionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Estado de Excepción IP',
                'verbose_name_plural': 'Estados de Excepciones IP',
                'db_table': 'ip_exception_status',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='IpException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(verbose_name='Válido desde')),
                ('valid_until', models.DateField(verbose_name='Válido hasta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ip_control.ipexceptionstatus', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Excepción IP',
                'verbose_name_plural': 'Excepciones IP',
                'db_table': 'ip_exception',
            },
        ),
        migrations.CreateModel(
            name='IpExceptionAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.assistant', verbose_name='Asistente')),
                ('ip_exception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='ip_control.ipexception', verbose_name='Excepción')),
            ],
            options={
                'verbose_name': 'Asistente en Excepción',
                'verbose_name_plural': 'Asistentes en Excepciones',
                'db_table': 'ip_exception_assistant',
                'unique_together': {('ip_exception', 'assistant')},
            },
        ),
    ]
